version: '3'

services:
  frontend:
    image: frontend
    ports:
      - 5000:5000
  backend:
    image: backend
    ports:
      - 8000:8000
    environment:
      - REDIS=redis
      - REDIS_PORT=6379
  redis:
    image: redis
    expose:
      - 6379
