version: '3'

services:
  redis:
      image: redis
      restart: unless-stopped
      ports:
        - "6379:6379"
  db:
      image: postgres
      restart: unless-stopped
      environment:
        - POSTGRES_USER=userone
        - PGPASSWORD=pwd1
      volumes:
        - ./postgres-data:/var/lib/postgresql/data  
  frontend:
      build: ./frontend-example-docker
      expose:
        - "5000"
      ports:
        - "5000:5000"
      environment: 
        - API_URL=http://localhost:8000
      container_name: frontend_example
      depends_on:
        - backend
  backend:
      build: ./backend-example-docker
      links:
        - redis
        - db
      expose:
        - "8000"
      ports:
        - "8000:8000"
      environment:
        - FRONT_URL=http://localhost:5000
        - REDIS=redis
        - DB_USERNAME=userone
        - DB_PASSWORD=pwd1
        - DB_HOST=db
      container_name: backend-example
