version: '3'  

services: 
  frontend: 
    image: training_frontend
    build:
      context: https://github.com/docker-hy/ml-kurkkumopo-frontend.git
      dockerfile: Dockerfile
    ports: 
      - 3000:3000

  backend: 
    image: training_backend
    build:
      context: https://github.com/docker-hy/ml-kurkkumopo-backend.git
      dockerfile: Dockerfile
    ports: 
      - 5000:5000
    volumes:
      - ./model:/src/model
    depends_on:
      - training
    
  training:
    image: training
    build:
      context: https://github.com/docker-hy/ml-kurkkumopo-training.git
      dockerfile: Dockerfile
    volumes:
      - ./model:/src/model
      - ./imgs:/src/imgs
