version: '3'

services:
  proxy: 
    image: jwilder/nginx-proxy 
    volumes: 
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports: 
      - 80:80
    depends_on:
      - frontend

  frontend:
    image: frontend
    expose:
      - 5000
    environment:
      - API_URL=http://localhost/api:80
    depends_on:
      - backend
  backend:
    image: backend
    expose:
      - 8000
    environment:
      - REDIS=redis
      - REDIS_PORT=6379
      - DB_USERNAME=userone
      - DB_PASSWORD=pwd1
      - DB_HOST=database
    depends_on:
      - database
  redis:
    image: redis
    expose:
      - 6379

  database:
    image: postgres
    restart: unless-stopped
    environment: 
      - POSTGRES_USER=userone
      - POSTGRES_PASSWORD=pwd1
    container_name: database
    expose: 
      - 8000
